AllCops:
  NewCops: enable

  Exclude:
    - "**/Guardfile"
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "config/**/*"
  DisplayCopNames: false
  StyleGuideCopsOnly: false
