AllCops:
  Include:
    - "**/*.gemspec"
    - "**/*.podspec"
    - "**/*.jbuilder"
    - "**/*.rake"
    - "**/*.opal"
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/Capfile"
    - "**/Guardfile"
    - "**/Podfile"
    - "**/Thorfile"
    - "**/Vagrantfile"
    - "**/Berksfile"
    - "**/Cheffile"
    - "**/Vagabondfile"
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "config/**/*"
  DisplayCopNames: false
  StyleGuideCopsOnly: false
