@zines = 
[{ title: "How To Sink Whalers, Driftnetters, And Other Environmentally Destructive Ships", id: 1 }, 
{ title: "The ALF Primer", id: 2 }, 
{ title: "Frequently Asked Questions", id: 3 }, 
{ title: "Mini-Manual Of The Urban Guerrilla", id: 4 }, 
{ title: "If An Agent Knocks", id: 5 }, 
{ title: "Ward Churchill On Manifest Destiny", id: 6 }, 
{ title: "Future Primitive", id: 8 }, 
{ title: "Wasted Indeed", id: 9 }, 
{ title: "The Heretics Guide To The Bible", id: 10 }, 
{ title: "On The Legitimacy Of Property Destruction", id: 11 }, 
{ title: "Anti-Mass", id: 12 }, 
{ title: "Notes From The Underground", id: 13 }, 
{ title: "Two Essays On Youth Liberation", id: 14 }, 
{ title: "Animal Liberation", id: 15 }, 
{ title: "Anarchist Propaganda", id: 16 }, 
{ title: "The Individual, Society and the State", id: 17 }, 
{ title: "Women And Imprisonment In The U.S.", id: 18 }, 
{ title: "Going Underground For Animal Liberation", id: 19 }, 
{ title: "Poetic Terrorism And Art Sabotage", id: 20 }, 
{ title: "ExFURminating the Fur Industry", id: 21 }, 
{ title: "Anarchism", id: 22 }, 
{ title: "For Aboriginal Sovereignty", id: 23 }, 
{ title: "Two Talks On Neo-Liberalism", id: 24 }, 
{ title: "Classic City Chaos", id: 56 }, 
{ title: "Durruti Is Dead, Yet Living", id: 25 }, 
{ title: "A.L.F. Bulletin To All Fur Farm Raiders", id: 26 }, 
{ title: "Dykes And Fags Want To Know...", id: 27 }, 
{ title: "A Fighting Chance", id: 28 }, 
{ title: "Trotsky Protests Too Much", id: 29 }, 
{ title: "Dear Motorist", id: 30 }, 
{ title: "Beyond Squat or Rot", id: 31 }, 
{ title: "Where Does the Gas Come From?", id: 32 }, 
{ title: "Feminism As Anarchism", id: 33 }, 
{ title: "Building a Revolutionary Movement", id: 34 }, 
{ title: "Fauxvertising, Fsu-Ism And Other Semiotic Attacks On Consensual Reality", id: 35 }, 
{ title: "The Shooting Of Henry Clay Frick By Alexander Berkman", id: 36 }, 
{ title: "You Can't Blow Up A Social Relationship", id: 37 }, 
{ title: "Sun Tzu On The Art Of War", id: 38 }, 
{ title: "Rod's Experience With Government Harassment", id: 39 }, 
{ title: "Mommy's a WHAT?", id: 40 }, 
{ title: "A Future Worth Living", id: 107 }, 
{ title: "To The Wanderers", id: 41 }, 
{ title: "Guerilla Warfare", id: 42 }, 
{ title: "Direct Action", id: 43 }, 
{ title: "Science, Society & Religion", id: 44 }, 
{ title: "Anarcho-Feminism", id: 45 }, 
{ title: "Dialogue Between A Priest And A Dying Man", id: 46 }, 
{ title: "Civilization Will Eat Itself", id: 47 }, 
{ title: "The War Machine Continues...", id: 48 }, 
{ title: "ALF A,B,C'S", id: 49 }, 
{ title: "Non-Violence And It's Violent Consequences", id: 50 }, 
{ title: "Defining Terrorism", id: 51 }, 
{ title: "The Boss Needs Us. We Don't Need the Boss.", id: 52 }, 
{ title: "D.I.Y. Guide I", id: 53 }, 
{ title: "Shoplifting", id: 54 }, 
{ title: "Anarchism", id: 55 }, 
{ title: "Building a Revolutionary Movement", id: 57 }, 
{ title: "Derrick Jensen on...", id: 58 }, 
{ title: "Notes on Anarchism", id: 59 }, 
{ title: "God and the State", id: 60 }, 
{ title: "The Nighttime Gardener's Guide", id: 61 }, 
{ title: "Creating A Security Culture", id: 62 }, 
{ title: "The Animal Liberation Movement", id: 63 }, 
{ title: "Anarchism", id: 64 }, 
{ title: "Noam Chomsky on Anarchism, Marxism and Hope for the Future", id: 65 }, 
{ title: "Beyond Civil Disobedience", id: 66 }, 
{ title: "We All Live in Bhopal", id: 67 }, 
{ title: "North American Fur Farm List", id: 68 }, 
{ title: "Back From Hell", id: 69 }, 
{ title: "Marriage and Love", id: 70 }, 
{ title: "After Winter Must Come Spring", id: 71 }, 
{ title: "Joe Hill", id: 72 }, 
{ title: "Voltairine deCleyre", id: 73 }, 
{ title: "At the Center of the Volcano", id: 74 }, 
{ title: "Sabotage", id: 75 }, 
{ title: "Dropping Out", id: 76 }, 
{ title: "The Tragedy of the Political Exiles", id: 77 }, 
{ title: "Deportation => Its Meaning and Menace", id: 78 }, 
{ title: "Around the Camp FIre", id: 79 }, 
{ title: "Was My Life Worth Living?", id: 80 }, 
{ title: "Listen, Anarchist!", id: 81 }, 
{ title: "ALF Prisoner Support", id: 82 }, 
{ title: "Notes On Summits And Counter-Summits", id: 83 }, 
{ title: "Saint Che", id: 84 }, 
{ title: "20 Ways To Sabotage Your School", id: 108 }, 
{ title: "Why Anti-Authoritarian?", id: 85 }, 
{ title: "Open The Cages!", id: 86 }, 
{ title: "Against The Legalization Of Occupied Spaces", id: 87 }, 
{ title: "Laughter Is Bourgeoiis", id: 88 }, 
{ title: "Grand Juries", id: 89 }, 
{ title: "Introducing Anarcho-Syndicalism", id: 90 }, 
{ title: "On Order", id: 91 }, 
{ title: "CrimethInc. Worker Bulletin #47", id: 92 }, 
{ title: "The Anarchist Subculture", id: 93 }, 
{ title: "The Art & Science of Billboard Improvement", id: 94 }, 
{ title: "Mutual Aid", id: 95 }, 
{ title: "Insurrectionary Anarchy", id: 96 }, 
{ title: "The Anarchist Subculture", id: 97 }, 
{ title: "Noam Chomsky on Anarchism", id: 98 }, 
{ title: "The Disgust of 'Daily Life'", id: 126 }, 
{ title: "Direct Action For Animal Rights", id: 99 }, 
{ title: "Security Culture", id: 100 }, 
{ title: "We Never Sleep", id: 101 }, 
{ title: "10 Big Myths About Copyright Explained", id: 102 }, 
{ title: "Until All Are Free", id: 103 }, 
{ title: "Trial Statement of New Afrikan Revolutionary Kuwasi Balagoon", id: 104 }, 
{ title: "500 Years of Indigenous Resistance", id: 105 }, 
{ title: "A Brief History Of The Democratic Party", id: 106 }, 
{ title: "A Day Mournful & Overcast...", id: 109 }, 
{ title: "Women Prisoners' Resource Guide", id: 110 }, 
{ title: "100 Ways To Disappear & Live Free", id: 111 }, 
{ title: "Whats Wrong With Cars", id: 112 }, 
{ title: "Anarchy", id: 113 }, 
{ title: "20 Reasons To Abandon Christianity", id: 114 }, 
{ title: "A Primitivist Primer", id: 115 }, 
{ title: "ABC's of Anarchism", id: 116 }, 
{ title: "The Fight For History / Combate Por La Historia", id: 117 }, 
{ title: "Thirty Years of Direct Action", id: 118 }, 
{ title: "The Power Of The People Is The Force Of Life", id: 119 }, 
{ title: "We Want Our Freedom Anyway!", id: 120 }, 
{ title: "Weeping Willow", id: 121 }, 
{ title: "The Invisibility of Women Prisoners' Activism", id: 122 }, 
{ title: "This is What Democracy Looks Like", id: 123 }, 
{ title: "Resistance Ascending", id: 124 }, 
{ title: "The Continuing Appeal of Nationalism", id: 125 }, 
{ title: "Essays from the Minister of Defense", id: 127 }, 
{ title: "A Primer on Gentrification in Portland", id: 128 }, 
{ title: "Against All Odds", id: 129 }, 
{ title: "Media Geek", id: 130 }, 
{ title: "Rent", id: 131 }, 
{ title: "Does God Exist?", id: 132 }, 
{ title: "Keep Fighting", id: 133 }, 
{ title: "Anarchism, Ideology & Same Sex Desire", id: 134 }, 
{ title: "Models of Revolution", id: 135 }, 
{ title: "Fighting Back", id: 136 }, 
{ title: "Back to the Roots", id: 137 }, 
{ title: "Guerilla War Lit. 101", id: 138 }, 
{ title: "New Afrikan Criminology Journal", id: 139 }, 
{ title: "Mother Rebel", id: 140 }, 
{ title: "From Reform to Revolution", id: 141 }, 
{ title: "An Incomplete Guide to Rideable Freight Cars", id: 142 }, 
{ title: "May The Farce Be With You", id: 143 }, 
{ title: "Break de Chains", id: 144 }, 
{ title: "Reflections on Student Activism", id: 145 }, 
{ title: "God Eating", id: 146 }, 
{ title: "Art of Liberation", id: 147 }, 
{ title: "Memories of Freedom", id: 148 }, 
{ title: "Colonization", id: 149 }, 
{ title: "The False Principle of Our Education", id: 150 }, 
{ title: "Eat My Dust", id: 151 }, 
{ title: "Race Gender and Class", id: 152 }, 
{ title: "America's Taliban In Its Own Words", id: 153 }, 
{ title: "Pirate Riot", id: 154 }, 
{ title: "Heat Seeker", id: 155 }, 
{ title: "Not Really Better", id: 156 }, 
{ title: "Communique to the Radical Community of (Portland) PDX", id: 157 }, 
{ title: "The CIA Makes Science Fiction Unexciting", id: 158 }, 
{ title: "A Very Abbreviated List of Resources to Protect the Earth at a Variety of Levels", id: 159 }, 
{ title: "On Revolution", id: 160 }, 
{ title: "Rape Awareness List For Men / How A Rape‑Free World Could Benefit Men", id: 161 }, 
{ title: "Futur Primitiu", id: 162 }, 
{ title: "Firewood #1", id: 163 }, 
{ title: "The Royal Thai Massacres", id: 164 }, 
{ title: "Enemies of the State", id: 165 }, 
{ title: "ATR Activism", id: 166 }, 
{ title: "Loving Your Body / Fat Positivity To-Do List", id: 168 }, 
{ title: "THE A-WORD", id: 167 }, 
{ title: "Libres y Salvages", id: 169 }, 
{ title: "Guerrila Shit Composting", id: 7 }]
