common: &common
  adapter: <%= ENV.fetch('RAILS_DB_ADAPTER', 'mysql') %>
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch('RAILS_DB_HOST', 'localhost') %>
  port: <%= ENV.fetch("RAILS_DB_PORT", 3306) %>
  username: <%= ENV.fetch('RAILS_DB_USERNAME', 'root') %>

development:
  <<: *common
  database: zinedistro_development

test:
  <<: *common
  database: zinedistro_test

production:
  <<: *common
  database: zinedistro_production
